apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: docker.io/sukhman78/ecommerce-deployment:discovery-service-5aec2a9d6b2044844c4331e4f03dfa1d01e19685
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
