apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: docker.io/sukhman78/ecommerce-deployment:discovery-service-4f9b0fcd36282e3d3bdfa9f930c140f0a55aad20
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
